// J24 search + category navigation, J25 cart add/update/remove with stale-line revalidation.
import { call, check, Customer, journey, log, pub, RUN, S, sellable, section, setPrice, setStock, uiSignIn, visitor, activate } from './support'
import { shot, uiAdd, uiCustomer, uiDeliverHere, uiDelivery } from './web'

journey('J24', 'search and category navigation on the storefront (real browser)', async ({ page }) => {
  await visitor(page)
  const api = await pub('/v1/search?q=basmati&pin=560001')
  check('backend search "basmati" returns the seeded basmati products', ['TZP-E2E-RICE5', 'TZP-E2E-RICE1'].every((id) => (api.body.items ?? []).some((x: any) => x.productId === id)), (api.body.items ?? []).map((x: any) => x.productId))
  check('search is prefix-per-word and finds nothing for a random token', (await pub('/v1/search?q=zzqxv')).body.items?.length === 0)
  await page.goto('/')
  await page.locator('#site-search').fill('basmati')
  await page.locator('form[role="search"]').press('Enter')
  await page.waitForURL(/\/search\?q=basmati/)
  check('header search box navigates to /search?q=basmati', new URL(page.url()).searchParams.get('q') === 'basmati')
  check('results page lists the basmati cards', (await page.locator('article.card[data-product-id="TZP-E2E-RICE5"]').count()) === 1 && (await page.locator('article.card[data-product-id="TZP-E2E-RICE1"]').count()) === 1)
  check('and not the Sona Masoori product', (await page.locator('article.card[data-product-id="TZP-E2E-SONA"]').count()) === 0)
  await shot(page, 'j24-search')
  await page.locator('article.card[data-product-id="TZP-E2E-RICE5"] a').first().click()
  await page.waitForURL(/\/p\/TZP-E2E-RICE5/)
  check('clicking a result opens its PDP', (await page.locator('article.pdp h1').innerText()).includes('E2E Basmati Rice 5 kg'))
  await page.goto('/search?q=zzqxv')
  check('no match shows the empty message', (await page.getByRole('status').filter({ hasText: 'No products match' }).count()) === 1)
  await page.goto('/search?q=a')
  check('1-character query shows the 2..64 hint without calling the backend', (await page.locator('body').innerText()).includes('2 to 64 characters'))
  const odd = await page.goto('/search?q=' + encodeURIComponent('<script>alert(1)</script>'))
  check('markup in the query is rejected gracefully (200 page, hint, no script executed)', odd?.status() === 200 && !(await page.locator('body').innerHTML()).includes('<script>alert'), odd?.status())
  section('category navigation: home categories -> vertical -> product')
  await page.goto('/c/TZC-000001')
  const links = await page.locator('nav[aria-label="Sub-categories"] a').evaluateAll((as) => as.map((a) => (a as HTMLAnchorElement).getAttribute('href')))
  check('parent category lists its sub-categories as links', links.length >= 2, links)
  await page.goto('/c/TZG-000001')
  await page.locator('nav[aria-label="Sub-categories"] a', { hasText: 'Basmati Rice' }).first().click()
  await page.waitForURL(/\/c\/TZV-000001/)
  check('group -> vertical navigation reaches /c/TZV-000001', (await page.locator('#category-title').innerText()) === 'Basmati Rice')
  check('vertical page lists seeded products with prices', (await page.locator('article.card[data-product-id="TZP-E2E-RICE5"]').innerText()).includes('249'))
  await page.locator('article.card[data-product-id="TZP-E2E-RICE5"] a').first().click()
  await page.waitForURL(/\/p\/TZP-E2E-RICE5/)
  check('category -> PDP', true)
  const pg = await pub('/v1/categories/TZV-000001/products?pin=560001&page_size=1')
  check('cursor paging: page_size=1 returns a nextCursor and the next page differs', Boolean(pg.body.nextCursor) && (await pub(`/v1/categories/TZV-000001/products?pin=560001&page_size=1&cursor=${encodeURIComponent(pg.body.nextCursor)}`)).body.items?.[0]?.productId !== pg.body.items[0].productId)
})

journey('J25', 'cart add / update / remove with stale-line revalidation after admin price and stock changes', async ({ page }) => {
  const id = `TZP-E2E-K${RUN}`
  const id2 = `TZP-E2E-KR${RUN}`
  await sellable(id, `E2E Cart Rice ${RUN}`, { sell: 20000, mrp: 25000, stock: 10 })
  await sellable(id2, `E2E Cart Retire ${RUN}`, { sell: 5000, mrp: 6000, stock: 10 })
  await visitor(page)
  await uiCustomer(page, uiSignIn)
  await uiDeliverHere(page) // the saved address becomes the delivery location: the cart then reads stock + delivery for it
  await uiAdd(page, id)
  await uiAdd(page, id2)
  await page.goto('/cart')
  const line = (sku: string) => page.locator(`li.cart-line[data-product-id="${sku}"]`)
  check('cart page shows both lines and subtotal ₹250', (await line(id).count()) === 1 && (await line(id2).count()) === 1 && (await page.getByTestId('cart-subtotal').innerText()).includes('250'), await page.getByTestId('cart-subtotal').innerText())
  await page.getByRole('button', { name: `Increase quantity of E2E Cart Rice ${RUN}` }).click()
  await page.getByTestId('cart-subtotal').filter({ hasText: '450' }).waitFor({ timeout: 10_000 })
  check('update quantity to 2 via the stepper -> subtotal ₹450', true)
  await shot(page, 'j25-cart-1')

  section('admin raises the price while the line sits in the cart')
  const pr = await call('GET', `/api/v1/admin/prices/${id}`)
  await setPrice(id, 24000, 25000, pr.body.version)
  await page.reload()
  check('the cart shows the CURRENT price (₹240 x 2 + ₹50 = ₹530), never the stale one', (await page.getByTestId('cart-subtotal').innerText()).includes('530') && (await line(id).innerText()).includes('240'), await page.getByTestId('cart-subtotal').innerText())
  log('  note: the "price changed since you added this" line note (PRICE_CHANGED) is only raised for an AGING cart (freshness REVALIDATE, CartEnricher); a fresh cart just shows the current price')

  section('admin cuts stock below the quantity')
  const st = await call('GET', `/api/v1/admin/inventory/${id}/FL-E2E-1`)
  await setStock(id, 1, { expectedVersion: st.body.version, maxPurchasable: 1 })
  await page.reload()
  const txt = await line(id).innerText()
  check('the line is flagged: "Only 1 available. Lower the quantity to continue." and blocked', txt.includes('Only 1 available') && (await line(id).getAttribute('data-blocked')) === 'true', txt)
  check('the cart announces "1 item needs your attention before you can buy"', (await page.getByTestId('cart-blocked').innerText()).includes('1 item needs'))
  await page.goto('/checkout')
  check('and /checkout does NOT offer to place the order while a line is blocked', (await page.getByTestId('checkout-place').count()) === 0, page.url())
  await page.goto('/cart')
  await shot(page, 'j25-cart-blocked')
  await page.getByRole('button', { name: `Decrease quantity of E2E Cart Rice ${RUN}` }).click()
  await page.getByTestId('cart-subtotal').filter({ hasText: '290' }).waitFor({ timeout: 10_000 })
  check('lowering the quantity to 1 clears the block (subtotal ₹290)', (await line(id).getAttribute('data-blocked')) === 'false')

  section('admin takes stock to zero, and retires the other product')
  const st2 = await call('GET', `/api/v1/admin/inventory/${id}/FL-E2E-1`)
  await setStock(id, 0, { expectedVersion: st2.body.version, maxPurchasable: 1 })
  const g = await call('GET', `/api/v1/products/${id2}`)
  const ret = await call('POST', `/api/v1/products/${id2}/retire`, { body: { reason: 'e2e' }, headers: { 'If-Match': String(g.body.version) } })
  check('retire product -> 200', ret.status === 200, ret.status)
  await page.reload()
  check('line 1: "Out of stock."', (await line(id).innerText()).includes('Out of stock'))
  check('line 2 (retired): "No longer available. Remove it to continue."', (await line(id2).innerText()).includes('No longer available'))
  await line(id2).getByRole('button', { name: /^Remove/ }).click()
  await line(id2).waitFor({ state: 'detached', timeout: 10_000 })
  await line(id).getByRole('button', { name: /^Remove/ }).click()
  await page.locator('.cart-empty').waitFor({ timeout: 10_000 })
  check('removing both lines empties the cart', true)

  section('price changes between the review page and the click on Place order: explicit re-confirmation, then the new total')
  const id3 = `TZP-E2E-KP${RUN}`
  await sellable(id3, `E2E Cart Reprice ${RUN}`, { sell: 20000, mrp: 25000, stock: 10 })
  await uiAdd(page, id3)
  await uiDelivery(page)
  check('review shows ₹200', (await page.getByTestId('checkout-total').innerText()).includes('200'))
  const p3 = await call('GET', `/api/v1/admin/prices/${id3}`)
  await setPrice(id3, 23000, 25000, p3.body.version)
  await page.getByTestId('checkout-place').click()
  await page.getByTestId('checkout-error').waitFor({ timeout: 20_000 })
  check('placing with a stale price is refused with "A price changed" and nothing is ordered', (await page.getByTestId('checkout-error').innerText()).includes('A price changed'), await page.getByTestId('checkout-error').innerText())
  check('the review states the change from ₹200 to ₹230', /200.*230/.test(await page.getByTestId('checkout-changed').innerText()), await page.getByTestId('checkout-changed').innerText())
  await page.getByTestId('checkout-place').click()
  await page.waitForURL(/\/orders\/ORD_[A-Za-z0-9_-]+\?placed=1$/, { timeout: 30_000 })
  check('after the explicit second click the order is placed at the NEW total ₹230', (await page.getByTestId('order-total').innerText()).includes('230'))
  const sess = await Customer.signIn()
  check('(control) a fresh customer cart is empty, version 0', (await sess.cart()).body.version === 0)
})
